# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - release/*
    - hotfix/*

    exclude:
    - main
    - dev

  batch: true

stages:
- stage: CIstage
  jobs:
  - job: BuildJob
    pool:
      vmImage: windows-latest
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'restore task'
      inputs:
        command: restore
        projects: $(project)
        feedsToUse: select

    - task: DotNetCoreCLI@2
      displayName: 'build task'
      inputs:
        command: build
        projects: $(project)
        arguments: -c $(buildConfig)
    
    - task: DotNetCoreCLI@2
      displayName: 'publish task'
      inputs:
        command: publish
        projects: $(project)
        arguments: -c $(buildConfig) -o $(build.artifactsdirectory)


    - task: PublishBuildArtifacts@1
      displayName: 'publish artifact task'
      inputs:
        ArtifactName: artifact
        publishLocation: Container
        PathtoPublish: $(build.artifactsdirectory)
