# https://aka.ms/yaml

trigger:
    branches:
        include:
        - main
        - release/*
        - dev

        exclude:
        - hotfix/* 
    batch: true

pr:
    branches:
        include:
        - release/*

        exclude:
        - dev
        - main
         

variables:
  BuildConfig: 'Debug'

pool:
  vmImage: windows-latest

stages:
- stage: CIBuild
  jobs:
  - job: BuildJob
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'restore task'
      inputs:
        command: restore
        projects: $(ProjectName)
        feedsToUse: select
    
    - task: DotNetCoreCLI@2
      displayName: 'build task'
      inputs:
        command: build
        projects: $(projectName)
        arguments: -c $(BuildConfig)

    - task: DotNetCoreCLI@2
      displayName: 'publish task'
      inputs:
        command: publish
        projects: $(ProjectName)
        arguments: -c $(buildConfig) -o $(Build.ArtifactsDirectory)

    - task: PublishBuildArtifacts@1
      displayName: 'publish artifact task'
      inputs:
        ArtifactName: 'mycalculatorapp'
        publishLocation: Container
        PathtoPublish: $(Build.ArtifactsDirectory)

- stage: Testing
  displayName: "test stage"
  condition: contains(variables['Build.SourceBranch'],'refs/heads/release/')
  dependsOn: CIBuild
  pool:
    vmName: windows-latest
  jobs:
  - deployment: 'deploytoTestVM'
    environment: 
      name: "VMdepo"
      resourceType: VirtualMachine
      tags: test
    strategy:
      runOnce:
        deploy:
          steps:
          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              EnableIIS: true
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: 'calculatorapp'
              WebsitePhysicalPath: '%SystemDrive%\inetpub\wwwroot'
              WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
              AddBinding: true
              Bindings: '{
                "bindings": [
                  {
                    "protocol": "https",
                    "ipAddress": "All Unassigned",
                    "port": "1500",
                    "hostname": "mycalculator.com",
                    "sslThumbprint": "ba33d9482b295efbc8c55881d301111dbde8168f",
                    "sniFlag": false
                  }
                ]
              }'
              ParentWebsiteNameForApplication: 'calculatorapp'
              ParentWebsiteNameForVD: 'calculatorapp'
          
          - task: PowerShell@2
            displayName: 'PowerShell script for ASP.NET'
            inputs:
              targetType: 'inline'
              script: |
                # Write your PowerShell commands here.
                Invoke-WebRequest "https://download.visualstudio.microsoft.com/download/pr/7d169ca8-2755-4870-b45c-bfc651013a77/46639ef8e327f00ab1a941288dd28abe/dotnet-hosting-8.0.7-win.exe" -OutFile  $env:temp\DotNetCore.WindowsHosting.exe
                Start-Process $env:temp\DotNetCore.WindowsHosting.exe -ArgumentList '/quiet' -Wait
              errorActionPreference: 'silentlyContinue'

          - task: IISWebAppDeploymentOnMachineGroup@0
            displayName: 'iis webapp hosting from buildArtifact'
            inputs:
              WebSiteName: 'calculatorapp'
              Package: '$(Pipeline.Workspace)/mycalculatorapp/*.zip'
              TakeAppOfflineFlag: true
              XmlTransformation: true
              XmlVariableSubstitution: true


- stage: Development
  displayName: "dev stage"
  condition: eq(variables['Build.SourceBranch'],'refs/heads/dev')
  dependsOn: CIBuild
  pool:
    vmName: windows-latest
  jobs:
  - job: 'ManualApprovalNeeded'
    pool: server
    displayName: 'ApprovalJob'
    timeoutInMinutes: 3
    steps:
    - task: ManualValidation@1
      displayName: 'Approval'
      inputs:
        notifyUsers: 'pratulp2580@hotmail.com'
        onTimeout: reject


  - deployment: 'deploytoDEVvm'
    dependsOn: 'ManualApprovalNeeded'
    environment: 
      name: "VMdepo"
      resourceType: VirtualMachine
      tags: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              EnableIIS: true
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: 'calculatorapp'
              WebsitePhysicalPath: '%SystemDrive%\inetpub\wwwroot'
              WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
              AddBinding: true
              Bindings: '{
                "bindings": [
                  {
                    "protocol": "http",
                    "ipAddress": "All Unassigned",
                    "port": "80",
                    "hostname": "calculator.com",
                    "sslThumbprint": "",
                    "sniFlag": false
                  }
                ]
              }'
              ParentWebsiteNameForApplication: 'calculatorapp'
              ParentWebsiteNameForVD: 'calculatorapp'
          
          - task: PowerShell@2
            displayName: 'PowerShell script for ASP.NET'
            inputs:
              targetType: 'inline'
              script: |
                # Write your PowerShell commands here.
                Invoke-WebRequest "https://download.visualstudio.microsoft.com/download/pr/7d169ca8-2755-4870-b45c-bfc651013a77/46639ef8e327f00ab1a941288dd28abe/dotnet-hosting-8.0.7-win.exe" -OutFile  $env:temp\DotNetCore.WindowsHosting.exe
                Start-Process $env:temp\DotNetCore.WindowsHosting.exe -ArgumentList '/quiet' -Wait
              errorActionPreference: 'silentlyContinue'

          - task: IISWebAppDeploymentOnMachineGroup@0
            displayName: 'iis webapp hosting from buildArtifact'
            inputs:
              WebSiteName: 'calculatorapp'
              Package: '$(Pipeline.Workspace)\**\*.zip'
              TakeAppOfflineFlag: true
              XmlTransformation: true
              XmlVariableSubstitution: true

- stage: Production
  displayName: "prod stage"
  condition: eq(variables['Build.SourceBranch'],'refs/heads/main')
  dependsOn: CIBuild
  pool:
    vmName: windows-latest
  jobs:
  - deployment: 'deploytoPRODvm'
    environment: 
      name: "VMdepo"
      resourceType: VirtualMachine
      tags: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              EnableIIS: true
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: 'calculatorapp'
              WebsitePhysicalPath: '%SystemDrive%\inetpub\wwwroot'
              WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
              AddBinding: true
              Bindings: '{
                "bindings": [
                  {
                    "protocol": "http",
                    "ipAddress": "All Unassigned",
                    "port": "80",
                    "hostname": "calculator.com",
                    "sslThumbprint": "",
                    "sniFlag": false
                  }
                ]
              }'
              ParentWebsiteNameForApplication: 'calculatorapp'
              ParentWebsiteNameForVD: 'calculatorapp'
          
          - task: PowerShell@2
            displayName: 'PowerShell script for ASP.NET'
            inputs:
              targetType: 'inline'
              script: |
                # Write your PowerShell commands here.
                Invoke-WebRequest "https://download.visualstudio.microsoft.com/download/pr/7d169ca8-2755-4870-b45c-bfc651013a77/46639ef8e327f00ab1a941288dd28abe/dotnet-hosting-8.0.7-win.exe" -OutFile  $env:temp\DotNetCore.WindowsHosting.exe
                Start-Process $env:temp\DotNetCore.WindowsHosting.exe -ArgumentList '/quiet' -Wait
              errorActionPreference: 'silentlyContinue'

          - task: IISWebAppDeploymentOnMachineGroup@0
            displayName: 'iis webapp hosting from buildArtifact'
            inputs:
              WebSiteName: 'calculatorapp'
              Package: '$(Pipeline.Workspace)\**\*.zip'
              TakeAppOfflineFlag: true
              XmlTransformation: true
              XmlVariableSubstitution: true

  - job: 'ManualApprovalNeeded'
    dependsOn: 'deploytoPRODvm'
    pool: server
    displayName: 'ApprovalJob'
    steps:
      - task: ManualValidation@1
        inputs:
          notifyUsers: 'pratulp2580@hotmail.com'
          instructions: 'Kindly check and confirm if any changes required before CICD process'
          onTimeout: reject
